Criado sa funções 'Conversion Functions (F1)'
UTFPR-SL/Py.Mantissa-Grupo-1 pull request #2
Opened 2021-03-26 21:25 UTC by tiagomarciano

A linguagem escolhida para implementação das funções `Conversion Functions (F1)` foi a Python 3.8.5.

2021-03-29 13:27 UTC, igorsteinmacher commented
@hugohfsouza @hugovelasco O grupo de voces deve avaliar esse aqui

2021-03-29 21:32 UTC, hugovelasco requested changes
Done!

2021-03-29 21:32 UTC, hugovelasco commented on assignPR/ConversionFunctions.py
> +    main()
Recomendaria a adição de mais uma linha para finalizar o arquivo devido o mal comportamento de algumas ferramentas, caso o código seja finalizado abruptamente.

2021-04-02 02:01 UTC, tiagomarciano commented on assignPR/ConversionFunctions.py
> +    main()
Linha adicionada conforme sugestão, aproveitamos para documentar os métodos e alterar os nomes das variáveis para deixar o código mais legível.

2021-04-06 13:32 UTC, merged